### ISSUE TITLE
Constant-time base64 decoder

### ISSUE THREAD

**Issue by krk** [simdutf/simdutf#426]
Hi! Is there a fast, constant-time base64 decoder implementation available?

ref. https://github.com/openssl/openssl/issues/15199#issuecomment-2147939386

**Comment by lemire** [comment]
The base64 decoder in `simdutf` is state-of-the-art and WHATWG standard compliant. It can decode base64 data at gigabytes per second.


As far as complexity analysis is concerned, a base64 decoder has to read N bytes and write N/3*4 (plus ou minus a few bytes) so the complexity must O(N). It is the best possible complexity.

**Comment by davidben** [comment]
Since this was linked from OpenSSL and seems to have caused some confusion, let me correct some things. This bug seems to have been filed under several misunderstandings.

First, "constant-time", in the context of cryptography, does not mean O(1). It's a horrible terminology collision. In cryptography, it means this thing:
https://www.bearssl.org/constanttime.html

It's pretty specialized and I would not expect a general-purpose base64 decoder to care or want to care about this. There is sometimes overlap with some SIMD techniques, but that's different from taking it as a requirement.

Second, as discussed on the OpenSSL bug, I would not expect OpenSSL's performance problems do not stem from the base64 decoder itself. At the input sizes and the usual performance budgets here, base64 decoding is not a huge part of the overhead. Where it is, one is better off fixing the system to not use PEM, than optimizing the base64 decoder. Rather, OpenSSL's performance problems seem to stem from some architectural mistakes they made around their plugin system, and especially how the plugin system interacts with decoders.

**Comment by lemire** [comment]
@davidben I am going to close this issue for now.
